### PR TITLE
Fancy Markdown-formatted README

### PR DESCRIPTION
**Pull request by jim-wong**

### CODE REVIEW

**Comment by Shidelicious** [comment]
SO I CAN JUST TYPE ANYTHING AND IT WILL SHOW UP HERE

**Comment by jim-wong** [comment]
WHEN YOU MOVE THE MOUSE AROUND THE MOUSE MOVES AROUND.

**Comment by Shidelicious** [comment]
HIS EXPRESSION WAS ONE OF MIXED TENSION AND RELEASE

**Comment by jim-wong** [comment]
ALL RIGHT, WHO INVITED DEKKO?

(By the way Julia was supposed to say that when we saw you guys the other night, but she lost her nerve).

**Comment by Shidelicious** [comment]
THIS STOPS NOW OR I'LL HAVE BOTH OF YOUR ASSES HAULED BEFORE THE OWLNET SYSTEM ADMINISTRATOR.

(That's okay, I forgot to put more quarters into Joe-Joe's SPICE-AYYYYYYYY meter.)

**Pull request merged**
